# Generated by Django 4.1.2 on 2022-10-14 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Crub", new_name="Employee",),
    ]
