name: Build and Zip Django Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Comprimir proyecto en ZIP
      run: |
        zip -r django_project_build.zip . -x "*.git*"
    
    - name: Guardar artefacto
      uses: actions/upload-artifact@v4
      with:
        name: django-project-zip
        path: django_project_build.zip
